# Generated by Django 4.1 on 2022-10-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abhilasha", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaintsm",
            name="description",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="complaintsm",
            name="title",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
