# Generated by Django 4.1 on 2022-08-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_rename_product_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
