# Generated by Django 4.1 on 2022-08-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="box2",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
