# Generated by Django 4.1 on 2022-10-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_example"),
    ]

    operations = [
        migrations.AddField(
            model_name="example",
            name="description",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
